### PR TITLE
Code Improvements: formatting and low-level refactorings

### PR DESCRIPTION
**Pull request by habaneraa**
Awesome work on researching Android functional bugs!

This pull request includes several minor improvements to the source code, aimed at enhancing readability and maintainability. These changes adhere to Python style conventions. Please take the time to thoroughly review these modifications to ensure that the code's semantics and functionality remain unchanged. 

 - Better indent
 - Format Python source code
 - Remove unused import statements/ reorder import statements
 - Use f-string/path.join instead of string concat
 - Reduce code nesting

If you have any questions or concerns, please feel free to let me know.

### CODE REVIEW

**Comment by Android-Functional-bugs-study** [comment]
Thanks for your P&R! GOOD JOB! I have reviewed these modifications and tested the new version. Thanks again! If you have new improvements, feel free to P&R

**Comment by habaneraa** [comment]
Thanks for your reviewing!

**Comment by tingsu** [comment]
@habaneraa Thanks for making contribution to this tool!  Are you also interstesting in developing GUI testing tools? RegDroid is a prototype. We welcome potential ideas or discussion on how to enhance or extend this tool.

**Comment by habaneraa** [comment]
@tingsu  Yeah, I am a student just beginning my studies and my research interests include finding functional bugs in Android apps. I learned about RegDroid via your recent empirical study published at ISSTA 2023. This paper presented so many insights into the real-world bugs in Android apps. In terms of improving differential testing tools like RegDroid, I think that better generated test input will lead to better results (improving both test efficiency and capability).

By the way, congratulations on receiving the distinguished paper award :)

**Comment by tingsu** [comment]
@habaneraa Thank you! To be clear, if you are interested in this field, you can contact us and we can discuss more. Maybe we can have some collaboration :)

**Pull request merged**
